//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int idCliente { get; set; }
        public string usuario { get; set; }
        public string Nome { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public Nullable<System.DateTime> dataAcesso { get; set; }
    }
}
