//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atividade04.Data.Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_hotelEntities : DbContext
    {
        public db_hotelEntities()
            : base("name=db_hotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbFuncionario> tbFuncionario { get; set; }
        public virtual DbSet<tbHospede> tbHospede { get; set; }
        public virtual DbSet<tbLogin> tbLogin { get; set; }
    }
}
