//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atividade04.Data.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLogin
    {
        public int id_usuario { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public bool status { get; set; }
    }
}
